In [1]:
import numpy as np
import pandas as pd
from mplsoccer import Pitch, VerticalPitch
import matplotlib.pyplot as plt
from matplotlib import animation

In [2]:
# convert timestamp column to seconds
def time_to_seconds(time_str):
    if pd.isna(time_str.any()):
        raise Exception("cannot be null")
    # need to remove the date from the timestamp column and get only time
    remove_date = np.array(time_str.apply(str.split).tolist()).T[1] # get just the time in h:m:s
    h, m, s = np.array(list(map(lambda x: x.split(":"), remove_date))).T # split on colon
    h, m, s = np.array(list(map(float, h))), np.array(list(map(float, m))), np.array(list(map(float, s))) # convert each value to int in all lists
    return h * 3600 + m * 60 + s # returns one array

In [3]:
# load data
data = pd.read_csv("../data/full_data.csv")
data.head()

C:\Users\miale.a\AppData\Local\Temp\ipykernel_15568\3577333053.py:2: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/full_data.csv")

,Unnamed: 0,player_id_event,match_id,frame_start,frame_end,event_id,event_type,team_id_event,player_in_possession_id,x_start,...,number,team_id_tracking,team_name,player_role.position_group,total_time,player_role.name,player_role.acronym,is_gk,direction_player_1st_half,direction_player_2nd_half
0,0,966120,1886347,28,28,8_0,player_possession,1805,NaN,0.73,...,1,1805,Newcastle United Jets FC,Other,5400,Goalkeeper,GK,True,left_to_right,right_to_left
1,1,966120,1886347,28,28,8_0,player_possession,1805,NaN,0.73,...,4,1805,Newcastle United Jets FC,Central Defender,5400,Right Center Back,RCB,False,left_to_right,right_to_left
2,2,966120,1886347,28,28,8_0,player_possession,1805,NaN,0.73,...,15,1805,Newcastle United Jets FC,Central Defender,5400,Left Center Back,LCB,False,left_to_right,right_to_left
3,3,966120,1886347,28,28,8_0,player_possession,1805,NaN,0.73,...,14,1805,Newcastle United Jets FC,Full Back,5400,Right Back,RB,False,left_to_right,right_to_left
4,4,966120,1886347,28,28,8_0,player_possession,1805,NaN,0.73,...,33,1805,Newcastle United Jets FC,Full Back,5400,Left Back,LB,False,left_to_right,right_to_left

In [6]:
print(data.columns)

Index(['Unnamed: 0', 'player_id_event', 'match_id', 'frame_start', 'frame_end',
       'event_id', 'event_type', 'team_id_event', 'player_in_possession_id',
       'x_start', 'y_start', 'x_end', 'y_end', 'x', 'y', 'player_id_tracking',
       'is_detected', 'frame', 'timestamp', 'period', 'possession_player_id',
       'possession_group', 'ball_x', 'ball_y', 'ball_z', 'is_detected_ball',
       'start_time', 'end_time', 'match_name', 'date_time', 'home_team.name',
       'away_team.name', 'id', 'short_name', 'number', 'team_id_tracking',
       'team_name', 'player_role.position_group', 'total_time',
       'player_role.name', 'player_role.acronym', 'is_gk',
       'direction_player_1st_half', 'direction_player_2nd_half'],
      dtype='object')

In [4]:
print(time_to_seconds(data[data["frame_start"]==45439]["timestamp"]))

[4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8
 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8 4346.8
 4346.8 4346.8]

In [5]:
print(time_to_seconds(data[data["frame_start"]==28]["timestamp"]))

[1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8
 1.8 1.8 1.8 1.8]

In [17]:
print(data[data["frame"]==58]) # need to get tracking data separate, this df only has the final frame of an event

        Unnamed: 0  player_id_event  match_id  frame_start  frame_end  \
22              22            51649   1886347           48         58
23              23            51649   1886347           48         58
24              24            51649   1886347           48         58
25              25            51649   1886347           48         58
26              26            51649   1886347           48         58
...            ...              ...       ...          ...        ...
330457      330457            50992   1953632           56         58
330458      330458            50992   1953632           56         58
330459      330459            50992   1953632           56         58
330460      330460            50992   1953632           56         58
330461      330461            50992   1953632           56         58

       event_id         event_type  team_id_event  player_in_possession_id  \
22          8_1  player_possession           1805                      NaN
23          8_1  player_possession           1805                      NaN
24          8_1  player_possession           1805                      NaN
25          8_1  player_possession           1805                      NaN
26          8_1  player_possession           1805                      NaN
...         ...                ...            ...                      ...
330457      7_3     passing_option           2380                   9520.0
330458      7_3     passing_option           2380                   9520.0
330459      7_3     passing_option           2380                   9520.0
330460      7_3     passing_option           2380                   9520.0
330461      7_3     passing_option           2380                   9520.0

        x_start  ...  number  team_id_tracking                 team_name  \
22       -22.31  ...       1              1805  Newcastle United Jets FC
23       -22.31  ...       4              1805  Newcastle United Jets FC
24       -22.31  ...      15              1805  Newcastle United Jets FC
25       -22.31  ...      14              1805  Newcastle United Jets FC
26       -22.31  ...      33              1805  Newcastle United Jets FC
...         ...  ...     ...               ...                       ...
330457   -17.12  ...       6              2380         Melbourne City FC
330458   -17.12  ...      13              2380         Melbourne City FC
330459   -17.12  ...      10              2380         Melbourne City FC
330460   -17.12  ...      38              2380         Melbourne City FC
330461   -17.12  ...      35              2380         Melbourne City FC

        player_role.position_group  total_time   player_role.name  \
22                           Other        5400         Goalkeeper
23                Central Defender        5400  Right Center Back
24                Central Defender        5400   Left Center Back
25                       Full Back        5400         Right Back
26                       Full Back        5400          Left Back
...                            ...         ...                ...
330457                    Midfield        5400      Left Midfield
330458                    Midfield        5400     Right Midfield
330459               Wide Attacker        2379      Right Forward
330460               Wide Attacker        4422       Left Forward
330461              Center Forward        5217     Center Forward

        player_role.acronym  is_gk direction_player_1st_half  \
22                       GK   True             left_to_right
23                      RCB  False             left_to_right
24                      LCB  False             left_to_right
25                       RB  False             left_to_right
26                       LB  False             left_to_right
...                     ...    ...                       ...
330457                   LM  False             right_to_left
330458                   RM  False             right_to_left
330459                   RF  False             right_to_left
330460                   LF  False             right_to_left
330461                   CF  False             right_to_left

        direction_player_2nd_half
22                  right_to_left
23                  right_to_left
24                  right_to_left
25                  right_to_left
26                  right_to_left
...                           ...
330457              left_to_right
330458              left_to_right
330459              left_to_right
330460              left_to_right
330461              left_to_right

[264 rows x 44 columns]

In [19]:
# Load Full Tracking Data
tracking_df = pd.read_json('../data/matches/1886347/1886347_tracking_extrapolated.jsonl', lines=True)
raw_df =pd.json_normalize(tracking_df.to_dict('records'), 'player_data',
                         ['frame','timestamp','period','possession','ball_data'])

# Clean Tracking Data
raw_df['possession_player_id'] = raw_df['possession'].apply(lambda x: x.get('player_id'))
raw_df['possession_group'] = raw_df['possession'].apply(lambda x: x.get('group'))
raw_df[['ball_x','ball_y','ball_z','is_detected_ball']]=pd.json_normalize(raw_df.ball_data)
raw_df = raw_df.drop(columns=['possession','ball_data'])
raw_df.head()

,x,y,player_id,is_detected,frame,timestamp,period,possession_player_id,possession_group,ball_x,ball_y,ball_z,is_detected_ball
0,-39.63,-0.08,51009,False,10,2026-03-31,1.0,NaN,None,0.32,0.38,0.13,True
1,-19.21,-9.18,176224,True,10,2026-03-31,1.0,NaN,None,0.32,0.38,0.13,True
2,-21.83,0.47,51649,True,10,2026-03-31,1.0,NaN,None,0.32,0.38,0.13,True
3,-1.16,-32.47,50983,True,10,2026-03-31,1.0,NaN,None,0.32,0.38,0.13,True
4,-18.88,15.73,735578,True,10,2026-03-31,1.0,NaN,None,0.32,0.38,0.13,True

In [28]:
# convert timestamp to seconds
raw_df["timestamp"] = list(map(lambda x: x.hour * 3600 + x.minute * 60 + x.second, raw_df["timestamp"]))

In [34]:
# need to convert to 1/0
print(raw_df["possession_group"].value_counts())

possession_group
home team    397078
away team    296406
Name: count, dtype: int64